name: praskripsi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies: 
  convex_bottom_bar: 3.2.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^14.0.0+1
  get: 4.6.5
  http: ^0.13.5
  loading_animation_widget: ^1.2.0+4
  shared_preferences: 2.1.0
  intl: 0.18.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

